from abc import ABC
from typing import List,Union
from src.modules.reserve.entity.reserve import Reserve
from src.modules.reserve.infrastructure.persistence.models import Reservations

class ReserveRepository(ABC):
    def save(self,movie:Reservations)->Reservations: ...

    def get_by_id(self, reserve_id: str)-> Union[Reservations,None]: ...

    def get_by_user_id(self, reserve_id: str)-> Union[Reservations,None]: ...

    def get_by_movie_id(self, reserve_id: str)-> Union[Reservations,None]: ...

    def get_all(self)-> Union[List[Reservations],None]: ...

    def get_by_user_id_and_movie_id(self,user_id:str,movie_id:str):...

    def to_dataclass(self,object,dataclass_type): ...

    def update_reserve_seat(self,reserve_id,user_reserve_seats,created_at):...

    def to_persistence_model(self,movie:Reserve)->Reservations:...
    
