from src.core.exceptions import (
    BaseApiException,
    NotFoundException,
    DuplicateResourceException,
    NotAvailableException,
    FailedToPersistException,
)

class ReserveNotFoundException(NotFoundException): ...

class DuplicateReserveException(DuplicateResourceException): ...

class FailedToSaveException(FailedToPersistException): ...

class FailedToSaveReserveException(FailedToSaveException): ...

class FailedToUnReserveExpection(BaseApiException): ...

class MovieNotAvailableException(NotAvailableException):...

class UserHasNoReservationException(ReserveNotFoundException): ...

class ReservationNotFoundException(NotFoundException): ...

class FailedToDeleteReserveException(FailedToPersistException):...

