from abc import ABC
from src.modules.movie.entity.movie import Movie
from typing import Union,List
from src.modules.movie.infrastructure.persistence.models import Movies

class MovieRepository(ABC):
    def save(self,movie:Movie)->Movie: ...

    def get_by_id(self, movie_id: str)-> Union[Movie,None]: ...

    def get_by_movie_name(self, movie_name: str)-> Union[Movie,None]: ...

    def get_all(self)-> Union[List[Movie],None]: ...

    def get_all_available(self)-> Union[List[Movies],None]:...

    def from_persistence(self,object,dataclass_type): ...

    def update_movie_seats_and_status(self,movie_id,reserve_seats,available_seats,movie_status):...

    def to_persistence(self,movie:Movie)->Movies:...
    
