from src.core.exceptions import BaseHttPException
from src.core.exceptions import DuplicateResourceException, FailedToSaveException, InvalidLoginException,InvalidInputEnteredException
from src.core.log_config import logger


class DuplicateUserException(DuplicateResourceException):...
    
class FailedToSaveUserException(FailedToSaveException): ...

class InvalidTokenException(InvalidInputEnteredException): ...

class InvalidUserNameException(InvalidLoginException): ...

class InvalidPasswordException(InvalidLoginException): ...

