from src.core.exceptions import BaseHttPException
from src.core.exceptions import DuplicateResourceException, FailedToSaveException, InvalidInputEnteredException
from src.core.log_config import logger


class DuplicateUserException(DuplicateResourceException):...
    
class FailedToSaveUserException(FailedToSaveException): ...

class InvalidTokenException(BaseHttPException): ...

class InvalidUsernamePasswordException(InvalidInputEnteredException): ...