from fastapi import HTTPException


class BaseApiException(Exception): ...

class BaseHttPException(HTTPException): ...

class DuplicateResourceException(BaseApiException): ...

class FailedToSaveException(BaseApiException): ...

class NotFoundException(BaseApiException): ...

class InvalidInputEnteredException(BaseApiException): ...

class InvalidLoginException(BaseApiException): ...

