from fastapi import HTTPException


class BaseApiException(Exception): ...

class BaseHttPException(HTTPException): ...

class DuplicateResourceException(BaseApiException): ...

class FailedToSaveException(Exception): ...

class NotFoundException(Exception): ...

class InvalidInputEnteredException(Exception): ...

